// <auto-generated />
namespace Evaluacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _190520192009 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_190520192009));
        
        string IMigrationMetadata.Id
        {
            get { return "201905200109458_19052019-2009"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
