// <auto-generated />
namespace Evaluacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _210720191840 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_210720191840));
        
        string IMigrationMetadata.Id
        {
            get { return "201907212340544_21072019-1840"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
