// <auto-generated />
namespace Evaluacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _280720191558 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_280720191558));
        
        string IMigrationMetadata.Id
        {
            get { return "201907282058495_28072019-1558"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
