// <auto-generated />
namespace Evaluacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _140520192308 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_140520192308));
        
        string IMigrationMetadata.Id
        {
            get { return "201905150409278_14052019-2308"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
