// <auto-generated />
namespace Evaluacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _150520191935 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_150520191935));
        
        string IMigrationMetadata.Id
        {
            get { return "201905160035124_15052019-1935"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
